server:
  port: 8081
  servlet:
    context-path: /springboot_shiro_mybatis

spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/CMCC?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&socketTimeout=60000
      db-type: com.alibaba.druid.pool.DruidDataSource     #����Դ��������Druid
      filters: stat                                       #�����������ַ�����ͨ�������ķ�ʽ������չ��������õĲ���У����ͳ���õ�filter:stat��־�õ�filter:log4j����sqlע���filter:wall
      max-active: 20                                      #������ӳ�����
      initial-size: 1                                     #��ʼ��ʱ�����������ӵĸ�������ʼ����������ʾ����init���������ߵ�һ��getConnectionʱ
      max-wait: 60000                                     #��ȡ����ʱ���ȴ�ʱ�䣬��λ����
      min-idle: 1
      time-between-eviction-runs-millis: 60000            #1) Destroy�̻߳������ӵļ��ʱ��2) testWhileIdle���ж����ݣ���ϸ��testWhileIdle���Ե�˵��
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'                        #������������Ƿ���Ч��sql��Ҫ����һ����ѯ��䡣���validationQueryΪnull��testOnBorrow��testOnReturn��testWhileIdle�����������á�
      test-while-idle: true                               #��������Ϊtrue����Ӱ�����ܣ����ұ�֤��ȫ�ԡ��������ӵ�ʱ���⣬�������ʱ�����timeBetweenEvictionRunsMillis��ִ��validationQuery��������Ƿ���Ч��
      test-on-return: false                               #�黹����ʱִ��validationQuery��������Ƿ���Ч������������ûή������
      test-on-borrow: false                               #��������ʱִ��validationQuery��������Ƿ���Ч������������ûή�����ܡ�
      pool-prepared-statements: false                     #�Ƿ񻺴�preparedStatement��Ҳ����PSCache��PSCache��֧���α�����ݿ����������޴󣬱���˵oracle����mysql�½���رա�
      max-open-prepared-statements: 20                    #Ҫ����PSCache���������ô���0��������0ʱ��poolPreparedStatements�Զ������޸�Ϊtrue����Druid�У��������Oracle��PSCacheռ���ڴ��������⣬���԰������ֵ���ô�һЩ������˵100
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  thymeleaf:
     cache: false
     mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.xwtech.entity
  mapper-locations: classpath:mapper/*/*.xml









